[[SoapyRTLSDR]]
arch = "aarch64"
git-tree-sha1 = "ddb30211b6f413948db5e940490abf8e020adf17"
os = "macos"

    [[SoapyRTLSDR.download]]
    sha256 = "bf32b3e48ebb2b6e8ad00b6b3e8b0c9146f9598784d9fc8a728d0b0e2bc2962b"
    url = "https://github.com/JuliaBinaryWrappers/SoapyRTLSDR_jll.jl/releases/download/SoapyRTLSDR-v0.3.301+0/SoapyRTLSDR.v0.3.301.aarch64-apple-darwin.tar.gz"
[[SoapyRTLSDR]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fef6452ccdd14830366806c5d9c680d5a99a10b4"
libc = "glibc"
os = "linux"

    [[SoapyRTLSDR.download]]
    sha256 = "32d5dfec5e7ca4bfee245084a554c38dcb04627a592f4a7b376ab2653ba10680"
    url = "https://github.com/JuliaBinaryWrappers/SoapyRTLSDR_jll.jl/releases/download/SoapyRTLSDR-v0.3.301+0/SoapyRTLSDR.v0.3.301.aarch64-linux-gnu-cxx11.tar.gz"
[[SoapyRTLSDR]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ac4d582f9f764d9421219d1df6b75d3728346c5d"
libc = "musl"
os = "linux"

    [[SoapyRTLSDR.download]]
    sha256 = "77c19970e3df4b5014210eee0ef848115920bf0a603d925280964a23cf76d1ab"
    url = "https://github.com/JuliaBinaryWrappers/SoapyRTLSDR_jll.jl/releases/download/SoapyRTLSDR-v0.3.301+0/SoapyRTLSDR.v0.3.301.aarch64-linux-musl-cxx11.tar.gz"
[[SoapyRTLSDR]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9083f3f0d5d9d4784cbd8ea8d64c6d0487589b8a"
libc = "glibc"
os = "linux"

    [[SoapyRTLSDR.download]]
    sha256 = "1490890ffc570f81ea7f6d351aaf8d2adf09a7795188e933995ddafbfe7cafee"
    url = "https://github.com/JuliaBinaryWrappers/SoapyRTLSDR_jll.jl/releases/download/SoapyRTLSDR-v0.3.301+0/SoapyRTLSDR.v0.3.301.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[SoapyRTLSDR]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0f794f4a8ca597ee80f6644392318efbccd5dfe4"
libc = "musl"
os = "linux"

    [[SoapyRTLSDR.download]]
    sha256 = "76180b44ab5657f9afba2d88df2c8b4cfc4ee5754f5a8351c143ded8320c6fd5"
    url = "https://github.com/JuliaBinaryWrappers/SoapyRTLSDR_jll.jl/releases/download/SoapyRTLSDR-v0.3.301+0/SoapyRTLSDR.v0.3.301.armv7l-linux-musleabihf-cxx11.tar.gz"
[[SoapyRTLSDR]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "16480ed6d9b3531b762fe3adf2a4270c94af89b2"
libc = "glibc"
os = "linux"

    [[SoapyRTLSDR.download]]
    sha256 = "e878adfbf300124dd6968752f7069524d0635cb1bb1337bb4f30ea95f5aa1352"
    url = "https://github.com/JuliaBinaryWrappers/SoapyRTLSDR_jll.jl/releases/download/SoapyRTLSDR-v0.3.301+0/SoapyRTLSDR.v0.3.301.i686-linux-gnu-cxx11.tar.gz"
[[SoapyRTLSDR]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d3ba5c9aa7e58fde989ae95850a90072fa5dd21b"
libc = "musl"
os = "linux"

    [[SoapyRTLSDR.download]]
    sha256 = "b080a43b9a36bc77477c368799c8724ff36a8dc9eeeb4aa21763c4ad10030c0c"
    url = "https://github.com/JuliaBinaryWrappers/SoapyRTLSDR_jll.jl/releases/download/SoapyRTLSDR-v0.3.301+0/SoapyRTLSDR.v0.3.301.i686-linux-musl-cxx11.tar.gz"
[[SoapyRTLSDR]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c96a66d0ce230a2240f617f994844e0d30374628"
os = "windows"

    [[SoapyRTLSDR.download]]
    sha256 = "d6f9ef15f9ed74be788f65665fd02665b291a48449101781f646ec45e0112fbc"
    url = "https://github.com/JuliaBinaryWrappers/SoapyRTLSDR_jll.jl/releases/download/SoapyRTLSDR-v0.3.301+0/SoapyRTLSDR.v0.3.301.i686-w64-mingw32-cxx11.tar.gz"
[[SoapyRTLSDR]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9beb633f4436484e07dd3362989b0998e79ccf67"
libc = "glibc"
os = "linux"

    [[SoapyRTLSDR.download]]
    sha256 = "81400a4a297b530feb396b6fbea09c030e505816f27ce4e6619990775a6bc653"
    url = "https://github.com/JuliaBinaryWrappers/SoapyRTLSDR_jll.jl/releases/download/SoapyRTLSDR-v0.3.301+0/SoapyRTLSDR.v0.3.301.powerpc64le-linux-gnu-cxx11.tar.gz"
[[SoapyRTLSDR]]
arch = "x86_64"
git-tree-sha1 = "05097e38dccb85d2153bbf4b7759c16d6b1a5753"
os = "macos"

    [[SoapyRTLSDR.download]]
    sha256 = "3f2f210eccc41ecd79accab621c451a6b9e47383d96649878dca38a7e490cecf"
    url = "https://github.com/JuliaBinaryWrappers/SoapyRTLSDR_jll.jl/releases/download/SoapyRTLSDR-v0.3.301+0/SoapyRTLSDR.v0.3.301.x86_64-apple-darwin.tar.gz"
[[SoapyRTLSDR]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0591469b767e907e41765d5cd7fade84b9da00b6"
libc = "glibc"
os = "linux"

    [[SoapyRTLSDR.download]]
    sha256 = "aea9f167209b7cca1a54f26725339b5003824f8c3b00a1abcc5e43a1c63f3417"
    url = "https://github.com/JuliaBinaryWrappers/SoapyRTLSDR_jll.jl/releases/download/SoapyRTLSDR-v0.3.301+0/SoapyRTLSDR.v0.3.301.x86_64-linux-gnu-cxx11.tar.gz"
[[SoapyRTLSDR]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c7b56113d92d89159c2d41dd3839c7b049fe6494"
libc = "musl"
os = "linux"

    [[SoapyRTLSDR.download]]
    sha256 = "7ae9a06d36123d4cdb5bcf3e03a2f129cba3627826e990adb7a74a5190cd8681"
    url = "https://github.com/JuliaBinaryWrappers/SoapyRTLSDR_jll.jl/releases/download/SoapyRTLSDR-v0.3.301+0/SoapyRTLSDR.v0.3.301.x86_64-linux-musl-cxx11.tar.gz"
[[SoapyRTLSDR]]
arch = "x86_64"
git-tree-sha1 = "8ad7891793da0ed1e6774962d57cf2e42772a4c1"
os = "freebsd"

    [[SoapyRTLSDR.download]]
    sha256 = "2121953fb69137dd9d9433d0266c1ff5fed2e52668fd893333a0524928bebc87"
    url = "https://github.com/JuliaBinaryWrappers/SoapyRTLSDR_jll.jl/releases/download/SoapyRTLSDR-v0.3.301+0/SoapyRTLSDR.v0.3.301.x86_64-unknown-freebsd.tar.gz"
[[SoapyRTLSDR]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5910adea19ee9b7c8d282f0855c402e4ae007e06"
os = "windows"

    [[SoapyRTLSDR.download]]
    sha256 = "34ccf7f75684d921363afde3e2747e19022eb28a2181db3c47335435988037ab"
    url = "https://github.com/JuliaBinaryWrappers/SoapyRTLSDR_jll.jl/releases/download/SoapyRTLSDR-v0.3.301+0/SoapyRTLSDR.v0.3.301.x86_64-w64-mingw32-cxx11.tar.gz"
